### PR TITLE
Update DumpSMBIOS.cpp

### PR DESCRIPTION
**Pull request by caizidong**
1. add some string about enum type.
2. add some element for processor info struct.
3. show more info for type22, type2 and etc.

### CODE REVIEW

**Comment by KunYi** [comment]
thanks @caizidong

**Review by KunYi — APPROVED** [review]
thanks @caizidong

**Comment by caizidong** [comment]
不用谢，想了解一下为什么要使用_tprintf，我觉得printf没啥区别啊。

**Comment by KunYi** [comment]
keep code style
original support on Unicode environments

**Pull request merged**
