### PR TITLE
Caizidong

### PR DESCRIPTION
**Pull request by caizidong**
show all oem string, not only the last string

### CODE REVIEW

**Comment by KunYi** [comment]
For keep clear log.
Would you merge two commit to one first? 

you can to usage the following instructions to doing.

 'git commit --amend'
or
'git squash' 

thank you.

**Comment by caizidong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by caizidong** [comment]
dear&nbsp;KunYi:
&nbsp; &nbsp; &nbsp;I have merged the two commits into once.Please Check my merge request soon.

**Comment by caizidong** [comment]
ok, thank you for your letter, i will do it soon.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KunYi/DumpSMBIOS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 上午9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KunYi/DumpSMBIOS] Caizidong (PR #8)





 
For keep clear log.
 Would you merge two commit to one first?
 
you can to usage the following instructions to doing.
 
'git commit --amend'
 or
 'git squash'
 
thank you.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
